# Generated by Django 3.0.4 on 2020-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
