# Generated by Django 3.0.4 on 2020-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_delikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='delikes',
            new_name='deslikes',
        ),
    ]
