# Generated by Django 3.0.4 on 2020-04-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postdeslike_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
