# Generated by Django 3.0.4 on 2020-09-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
