# Generated by Django 2.2.16 on 2020-09-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200906_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
